version: '3.8'

# Define the services for the application
services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - inpainting-network
    command: redis-server --appendonly yes
    hostname: redis

  # Service for PostgreSQL database
  postgres:
    image: postgres:15-alpine 
    hostname: postgres
    env_file:
      - ./.env
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - inpainting-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Python inference service
  python-inference:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - uploads:/usr/src/app/uploads
    networks:
      - inpainting-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Service for the main application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: inpainting-app:latest
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - ./.env
    environment:
      - PYTHON_SERVICE_URL=http://python-inference:5000
    volumes:
      - uploads:/usr/src/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      python-inference:
        condition: service_healthy
    networks:
      - inpainting-network
    restart: unless-stopped

  # Service for the background worker
  worker:
    image: inpainting-app:latest
    env_file:
      - ./.env
    environment:
      - PYTHON_SERVICE_URL=http://python-inference:5000
    command: npm run worker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      python-inference:
        condition: service_healthy
    networks:
      - inpainting-network
    restart: unless-stopped
    deploy:
      replicas: 2

# Define named volumes
volumes:
  uploads:
  postgres_data:
  redis_data:

# Define the networks
networks:
  inpainting-network:
    driver: bridge